name: Deploy Python App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/python-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/python-app:latest

      - name: Checkout private action repository
        uses: actions/checkout@v3
        with:
          repository: passionatedreamer99/BE_konnect_dashboard_python_server
          token: ${{ secrets.ACTION_PAT }}
          path: './BE_konnect_dashboard_python_server'

      - name: Deploy to Azure server App
        uses: ./BE_konnect_dashboard_python_server
        with:
          app-name: "konnectapi-server"
          images: "${{ secrets.AZURE_CONTAINER_REGISTRY }}/python-app:latest"
