name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        name: myapp-container
        image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest
        dns-name-label: myapp-${{ github.run_number }}
        location: eastus
        os-type: Linux
        ports: 2000